name: ris

services:
  db:
    restart: unless-stopped
    image: postgres:16.3-alpine3.20
    container_name: db
    ports:
      - 3030:5432

    shm_size: 128mb # set shared memory limit when using docker-compose

    volumes:
      - data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ris-user
      POSTGRES_PASSWORD: dummy
      POSTGRES_DB: ris_db

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      target: ${BUILD_TARGET:-production}
    volumes:
      - /app/node_modules
    container_name: backend
    depends_on:
      - db
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "3031:3001"
    command: ${START_CMD:-"node dist/index.js"}

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    tmpfs: /tmp
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - BACKEND_API_PROXY=http://backend:3000/**
    ports:
      - "3032:3000"

volumes:
    data:
