name: ris

services:
  db:
    restart: unless-stopped
    image: postgres:16.3-alpine3.20
    container_name: db
    ports:
      - 3030:5432

    shm_size: 128mb # set shared memory limit when using docker-compose

    volumes:
      - data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ris-user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ris_db

  backend:
    restart: unless-stopped
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - db
    env_file: .env
    ports:
      - "3031:3001"
    volumes:
      - ./backend/:/app

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    # env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - BACKEND_API_PROXY=${BACKEND_API_PROXY}
    ports:
      - "3032:3000"
      - "24678:24678"
      - "9229:9229"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.nuxt

volumes:
    data:
