services:
  backend:
    restart: always
    build:
      target: production
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    build:
      target: production
      args:
        - BACKEND_API_PROXY=http://backend:3000
    environment:
      - NODE_ENV=production
      - BACKEND_API_PROXY=http://backend:3000
