# This is for development!
#
# Run it like this:
#
# docker compose up --build -d
#
# Production would compose the main file, followed by another yaml file:
#
# docker compose -f compose.yaml -f compose.prod.yaml up --build -d

services:
  backend:
    build:
      target: development
    volumes:
      - ./backend/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - JWT_SECRET=nosecret
      - RIS_TEST_DATA=2024-09-04_testdata_projects_updated.json
      - LOKI_HOST=${LOKI_HOST}
    ports:
      - "3031:3001"
      - "51204:51204" # vitest, incl. UI
      - "3029:9229"   # debugger
    command: >
      sh -c "yarn debug"

  frontend:
    # build:
    #   target: development
    env_file: frontend/.env.dev
    environment:
      - BACKEND_API_PROXY="http://backend:3001/**"
    ports:
      - "3032:3000"
      - "24678:24678"
      - "9229:9229"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.nuxt
