# This is for development!
#
# Production would compose the main file, followed by another yaml file:
#
# docker --context ... compose \
#  -f compose.yaml -f compose.production.yaml \

services:
  backend:
    volumes:
      - ./backend/:/app
    environment:
      - NODE_ENV=development
      - PORT=3001
      - RIS_TEST_DATA=2024-09-04_testdata_projects_updated.json
    ports:
      - "3031:3001"
      - "51204:51204" # vitest, incl. UI
    command: >
      sh -c "yarn dev"

  frontend:
    environment:
      - NODE_ENV=development
      - BACKEND_API_PROXY=http://backend:3001/**
    ports:
      - "3032:3000"
      - "24678:24678"
      - "9229:9229"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.nuxt
