services:
  frontend:
    container_name: frontend-ci
    image: my-ci-test-frontend
    working_dir: /app
    environment:
        BACKEND_API_PROXY: http://backend-ci:3001

  playwright:
    container_name: playwright-ci
    image: my-ci-test-playwright
    depends_on:
      - frontend
    restart: "no"
    volumes:
      - ${GITHUB_WORKSPACE:-.}:/app
    working_dir: /app/frontend
    command: yarn playwright:ci
    environment:
      PLAYWRIGHT_BASE_URL: http://frontend-ci:3000
      PLAYWRIGHT_OUTPUT_DIR: test-results
