services:
  frontend:
    container_name: frontend-ci
    image: my-ci-test-frontend
    working_dir: /app
    environment:
        BACKEND_API_PROXY: http://backend-ci:3001

  playwright:
    container_name: playwright-ci
    image: my-ci-test-playwright
    depends_on:
      - frontend
    volumes:
      - ${GITHUB_WORKSPACE:-.}:/app
      - ./frontend/playwright-report:/app/frontend/playwright-report
      - /app/frontend/node_modules # The "Mask": Covers the node_modules part of the window
      # - /app/frontend/playwright-report
      # - /app/frontend/test-results
    working_dir: /app/frontend
    # command: npm run playwright:ci
    environment:
      PLAYWRIGHT_BASE_URL: http://frontend-ci:3000
