services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: ris-db
    ports:
      - 3030:5432

    shm_size: 128mb # set shared memory limit when using docker-compose

    volumes:
      - ris_db:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ris-user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ris_db
    secrets:
      - db_password

  backend:
    build:
      context: ../backend
    container_name: ris-backend
    depends_on:
      - db
    secrets:
      - db_password
      - fa_api_client_secret
      - ri_api_key
    env_file: "backend.env"
    ports:
      - "3031:3001"

  frontend:
    build:
      context: ../frontend
    depends_on:
      - backend
    container_name: ris-frontend
    ports:
      - "3032:3000"
      # - "24678:24678"

secrets:
   db_password:
     file: ../secrets/db_password.txt
   fa_api_client_secret:
     file: ../secrets/fa_api_client_secret.txt
   ri_api_key:
     file: ../secrets/ri_api_key.txt

volumes:
    ris_db:
