services:
  backend:
    volumes:
      - ../backend/:/app
    environment:
      - NODE_ENV=staging
      - RIS_TEST_DATA=2024-09-04_testdata_projects_updated.json
    env_file: "staging.env"

  frontend:
    volumes:
      - ../frontend/:/app
      - /app/node_modules/

    ports:
      - "3032:3000"
      - "24678:24678"
      - "9229:9229"
