services:
  backend:
    volumes:
      - ../backend/:/app
    environment:
      - NODE_ENV=staging
      - JWT_EXPIRES_IN=10m
    env_file: "staging.env"

  frontend:
    volumes:
      - ../frontend/:/app
      - /app/node_modules/

    ports:
      - "3032:3000"
      - "24678:24678"
      - "9229:9229"
