* RIS Documentation
** External documentation
https://documentation.forschungsdaten.at/

** Scripts
*** ./scripts/fd-openapi
Public, staging, api from the _forschungsdaten.at_ documentation harvested on [2024-04-10].

#+BEGIN_SRC shell
  curl https://cris-staging.aau.at/ris-synergy/info/v3/api-docs    | jq . > info.json
  curl https://cris-staging.aau.at/ris-synergy/project/v3/api-docs | jq . > project.json
  curl https://cris-staging.aau.at/ris-synergy/orgUnit/v3/api-docs | jq . > orgUnit.json
  curl https://cris-staging.aau.at/ris-synergy/funding/v3/api-docs | jq . > funding.json
#+END_SRC

#+BEGIN_SRC
  find . -type f -exec md5sum {} \; | sort -k 2

  3cec0ee2450bac0611d753599572306c  ./funding.json
  3d187ef05e6adecd1fc827da6f6c01e4  ./info.json
  8c3a79c5bb0d6be14bc6678ea4c31874  ./orgUnit.json
  242de744d12a9da865a886ebe4c43da4  ./project.json
#+END_SRC
** Tests
*** ./tests/samples
These samples are important from the FWF test API.

** PURE Api
[2024-06-25 Tue 09:22]
Create a system user in test and prod systems:

https://cris-test.univie.ac.at/admin/workspace/administrator/category/pure-api/page/user-api-keys/

Ensure your PURE API user has access to the `/users/*` permissions.

Run this script and create a System User with the username and email address:

yarn create-system-user <username> kirill.stytsenko@univie.ac.at

Then, create a API Key

User: <username>
Description: API key for the RIS "Import Tool" (test)
Accessible endpoints: /applications/*, /awards/*, /projects/*, /persons/*, /organizations/*, /external-organizations/*

Finally, save the API key in the `.env` for the PURE_API_KEY.

[2024-06-25 Tue 10:22]
the user can be created with the UI:
Create a username and email address.

These Accessible endpoints have been selected:

/applications/*
/awards/*
/external-organizations/*
/external-persons/*
/organizations/*
/persons/*
/projects/*
/users/*

Finally, save the API key in the `.env` for the PURE_API_KEY.
