name: Backend Tests

defaults:
  run:
    working-directory: ./backend

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  RIS_TEST_DATA: 2024-09-04_testdata_projects_updated.json

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'yarn'
        node-version: lts/*
        cache-dependency-path: ./backend/yarn.lock

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Generate Prisma client
      run: npx prisma generate

    - name: Run backend tests
      run: yarn test:ci
